# The Xcodegen config file
# Cấu hình thông tin dự án. Từ đây đi ra các config khác khi chạy mint init or mint xocde
name: iFast

include:
#  - xcodegen_templates/options.yml
- xcodegen_templates/packages.yml
- xcodegen_templates/target_templates.yml

options:
  minimumXcodeGenVersion: 2.42.0
  xcodeVersion: "13.3.1"

attributes:
  ORGANIZATIONNAME: miniapp

configs:
  Debug: debug
  Staging: debug
  Release: release

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 13.0
    SWIFT_VERSION: 5.0
    ENABLE_BITCODE: NO
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Staging:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: STAGING
      GCC_PREPROCESSOR_DEFINITIONS:
        - $(inherited)
        - STAGING=1
    Release:

targets:
  iFast:
    templates:
      - TargetTemplate
    sources:
      - path: iFast
      # - path: dist
#      - path: Licenses
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1.0.0
        #CODE_SIGN_ENTITLEMENTS: miniapp/miniapp.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: B79T985G2
        INFOPLIST_FILE: iFast/Info.plist
        TARGETED_DEVICE_FAMILY: 1
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.vtb.appointment
          DEVELOPMENT_TEAM: B79T985G2
          APP_DISPLAY_NAME: (DEV)iFast
          PRODUCT_NAME: DEV_iFast
          CODE_SIGN_IDENTITY: Apple Development
          PROVISIONING_PROFILE_SPECIFIER: miniappDev
        Staging:
          PRODUCT_BUNDLE_IDENTIFIER: com.vtb.miniapp.stg
          APP_DISPLAY_NAME: (STG)iFast
          PRODUCT_NAME: STG_miniappApp
          CODE_SIGN_IDENTITY: Apple Distribution
          PROVISIONING_PROFILE_SPECIFIER: vtb App Staging
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.vtb.miniapp.app
          APP_DISPLAY_NAME: iFast
          PRODUCT_NAME: iFast
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: miniapp App
  miniappTests:
   type: bundle.unit-test
   platform: iOS
   dependencies:
     - target: iFast
   sources:
     - path: miniappTests
   settings:
     base:
       ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
       BUNDLE_LOADER: $(TEST_HOST)
       CODE_SIGN_STYLE: Automatic
       INFOPLIST_FILE: miniappTests/Info.plist
     configs:
       Debug:
         TEST_HOST: $(BUILT_PRODUCTS_DIR)/DEV_miniappApp.app/DEV_miniappApp
       Staging:
         TEST_HOST: $(BUILT_PRODUCTS_DIR)/STG_miniappApp.app/STG_miniappApp
       Release:
         TEST_HOST: $(BUILT_PRODUCTS_DIR)/miniappApp.app/miniappApp
  miniappUITests:
   type: bundle.ui-testing
   platform: iOS
   dependencies:
     - target: iFast
   sources:
     - path: miniappUITests
   settings:
     base:
       ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
       CODE_SIGN_STYLE: Automatic
       TEST_TARGET_NAME: iFast
     configs:
       Debug:
       Staging:
       Release:

schemes:
  iFast:
    build:
      targets:
        iFast: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
